// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcGpD7cuBKOCGJLBGWG7bIW5O6wyqomc',
    appId: '1:84591744178:web:5050db06c76aef494025ab',
    messagingSenderId: '84591744178',
    projectId: 'tinytracks-349ae',
    authDomain: 'tinytracks-349ae.firebaseapp.com',
    storageBucket: 'tinytracks-349ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGLdy4lNjvSgXsCnZefJDHFx_5VInnx5E',
    appId: '1:84591744178:android:56c93ea0b6aaff454025ab',
    messagingSenderId: '84591744178',
    projectId: 'tinytracks-349ae',
    storageBucket: 'tinytracks-349ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClshlGmfOPsygA8Xaog2gzx3_d8Cbo1BA',
    appId: '1:84591744178:ios:ce44ce7313c9def84025ab',
    messagingSenderId: '84591744178',
    projectId: 'tinytracks-349ae',
    storageBucket: 'tinytracks-349ae.firebasestorage.app',
    iosBundleId: 'com.example.tinyTracks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClshlGmfOPsygA8Xaog2gzx3_d8Cbo1BA',
    appId: '1:84591744178:ios:ce44ce7313c9def84025ab',
    messagingSenderId: '84591744178',
    projectId: 'tinytracks-349ae',
    storageBucket: 'tinytracks-349ae.firebasestorage.app',
    iosBundleId: 'com.example.tinyTracks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWcGpD7cuBKOCGJLBGWG7bIW5O6wyqomc',
    appId: '1:84591744178:web:a7080229d1f29d6a4025ab',
    messagingSenderId: '84591744178',
    projectId: 'tinytracks-349ae',
    authDomain: 'tinytracks-349ae.firebaseapp.com',
    storageBucket: 'tinytracks-349ae.firebasestorage.app',
  );
}
